# storage_name          = ["stgaccountnameeastus","stgaccountnamecentralus","stgaccount3"]
# account_tier          = ["Standard","Standard","Standard"]
location              = "eastus2"
project               = "stg"
environment           = "dev"
prefix                = "ctc"
locationprefix        = ["est2"]
# rgname                = "example-rg-name"
vnetname              = ""
vnetCidr             = "10.0.0.0/16"
beSubnetCidr         = "10.10.0.0/24"
feSubnetCidr         = "10.20.0.0/24"
plsSubnetCidr        = "10.30.0.0/24"
gwsubnetcidr         = "10.40.0.0/24"
lbname               = "business-tier-lb"
lb_sku               = "Standard"
vmname               = "myvm-machine-01"